name = "claude-code-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
# Environment variables for development
# WARNING: Remove all real API keys before committing to version control!
# Production secrets should be set using: wrangler secret put ANTHROPIC_API_KEY
# OPENAI_API_KEY = "your-key-here"

# Map all Claude models to GPT-4o-mini
# HAIKU_MODEL_ID = "openai:gpt-4o-mini"
# SONNET_MODEL_ID = "openai:gpt-4o-mini"
# OPUS_MODEL_ID = "openai:gpt-4o-mini"

# Optional: Debug logging (set to "1" or "true" to enable)
DEBUG = "true"

[env.staging]
name = "claude-code-proxy-staging"

[env.production]
name = "claude-code-proxy-production" 