name = "claude-code-proxy"
main = "src/index.ts"

# Enable environment variables process.env support.
# https://developers.cloudflare.com/changelog/2025-03-11-process-env-support/
compatibility_date = "2025-04-01"
compatibility_flags = [
  "nodejs_compat",
  "nodejs_compat_populate_process_env",
]

[vars]
# Environment variables for development
# WARNING: Remove all real API keys before committing to version control!
# Production secrets should be set using: wrangler secret put ANTHROPIC_API_KEY

# API KEYS
# OPENAI_API_KEY = "sk-proj-..."
# OPENAI_API_BASE = "https://api.openai.com/v1"
# ANTHROPIC_API_KEY = "sky-ant-..."

# MODEL OVERRIDES
# HAIKU_MODEL_ID = "openai:gpt-4o-mini"
# SONNET_MODEL_ID = "openai:gpt-4o-mini"
# OPUS_MODEL_ID = "openai:gpt-4o-mini"

# Optional: Debug logging (set to "1" or "true" to enable)
DEBUG = "true"

[env.staging]
name = "claude-code-proxy-staging"

[env.production]
name = "claude-code-proxy-production" 